# Generated by Django 5.1.1 on 2024-10-04 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('service_provider', 'Service Provider'), ('consumer', 'Consumer')], max_length=20)),
                ('user_name', models.CharField(max_length=120)),
                ('user_age', models.IntegerField(default=0)),
                ('user_email', models.EmailField(max_length=254)),
                ('user_phone_number', models.CharField(max_length=120)),
                ('user_password', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_name', models.CharField(max_length=120)),
                ('appointment_date', models.DateField()),
                ('appointment_description', models.TextField()),
                ('appointment_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('appointment_location', models.TextField()),
                ('appointment_duration', models.TextField()),
                ('appointment_service_provider', models.ForeignKey(limit_choices_to={'user_type': 'service_provider'}, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='booking_services_app.user')),
            ],
        ),
    ]
