# Generated by Django 5.1.1 on 2024-10-18 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_services_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='appointment_consumer',
            field=models.ForeignKey(default=1998, limit_choices_to={'user_type': 'consumer'}, on_delete=django.db.models.deletion.CASCADE, related_name='booked_appointment', to='booking_services_app.user'),
            preserve_default=False,
        ),
    ]
